# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cdeae1a1667cdbb8dffca4a288dab9d14b883fce8b3047c61bac05ac7e22839ab6015f73cf3ada9e081f7bf5b241a8e9fa9dc4f26a066938167c84faa9065ff

test:
  secret_key_base: 79b44eb873d050ab71e174d3f82eb08c5e1c436b61c1af6fce25e6c356e2122599dc35a6be0acbb6e28fa6ba040b53335b011332b8590edfaa233e7bc2b87117

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
